//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
        [Display(Name = "Mã khách hàng")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public int MaKH { get; set; }


        [Display(Name = "Họ tên")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string HoTen { get; set; }


        [Required(ErrorMessage = "{0} không được để trống")]
        [Display(Name = "Tài khoản")]
        public string TaiKhoan { get; set; }


        [Required(ErrorMessage = "{0} không được để trống")]
        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }


        [Required(ErrorMessage = "{0} không được để trống")]
        [Display(Name = "Email")]
        public string Email { get; set; }


        [Required(ErrorMessage = "{0} không được để trống")]
        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }


        [Required(ErrorMessage = "{0} không được để trống")]
        [Display(Name = "Điện thoại")]
        public string DienThoai { get; set; }


        [Required(ErrorMessage = "{0} không được để trống")]
        [Display(Name = "Giới tính")]
        public string GioiTinh { get; set; }
        /*
        [Display(Name = "Ngày sinh")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgaySinh { get; set; }*/

        [Display(Name = "Ngày sinh")]
        [Required(ErrorMessage = "Vui lòng nhập Ngày sinh")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime NgaySinh { get; set; }

        [Display(Name = "Quyền")]
        public int quyen { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
