//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ThamGias = new HashSet<ThamGia>();
        }

        [Display(Name = "Mã sách")]

        public int MaSach { get; set; }
        [Display(Name = "Tên sách")]
        public string TenSach { get; set; }
        [Display(Name = "Giá bán")]
        public Nullable<decimal> GiaBan { get; set; }
        [Display(Name = "Mô tả")]
        public string MoTa { get; set; }
        [Display(Name = "Ảnh bìa")]
        public string AnhBia { get; set; }
        [Display(Name = "Ngày cập nhập")]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [Display(Name = "Số lượng tồn")]
        public Nullable<int> SoLuongTon { get; set; }
        [Display(Name = "Mã nhà xuất bản")]
        public Nullable<int> MaNXB { get; set; }
        [Display(Name = "Mã chủ đề")]
        public Nullable<int> MaChuDe { get; set; }
        [Display(Name = "Sách mới")]
        public Nullable<int> Moi { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ChuDe ChuDe { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThamGia> ThamGias { get; set; }
    }
}
